name = "journal-logs-frontend"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"
publish = "out"

[env.production]
vars = { API_BASE_URL = "https://journal-logs.akshayamohan-2401.workers.dev" }
